services:
  api:
    image: qlnp-api:latest
    container_name: qlnp-api
    ports:
      - "8003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=192.168.1.13,1439;Database=VI_NGHIPHEP;User Id=vietinfo;Password=Vietinfo@#@!;TrustServerCertificate=True"
      Jwt__SigningKey: "CHANGE_ME_AT_LEAST_32_CHARACTERS_LONG!"
