// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLNP.Api.Data;

#nullable disable

namespace QLNP.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLNP.Api.Shared.Domain.DmDonvi", b =>
                {
                    b.Property<long>("DonViId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DonViID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DonViId"));

                    b.Property<int?>("Cap")
                        .HasColumnType("int");

                    b.Property<long?>("CapDonViId")
                        .HasColumnType("bigint")
                        .HasColumnName("CapDonViID");

                    b.Property<string>("DiaChiDayDu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("DonViCapChaId")
                        .HasColumnType("bigint")
                        .HasColumnName("DonViCapChaID");

                    b.Property<long?>("DuongId")
                        .HasColumnType("bigint")
                        .HasColumnName("DuongID");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("LoaiDonViId")
                        .HasColumnType("bigint")
                        .HasColumnName("LoaiDonViID");

                    b.Property<string>("Longitude")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaDonVi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long?>("PhuongXaId")
                        .HasColumnType("bigint")
                        .HasColumnName("PhuongXaID");

                    b.Property<long?>("QuanHuyenId")
                        .HasColumnType("bigint")
                        .HasColumnName("QuanHuyenID");

                    b.Property<string>("SoNha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenDonVi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TenVietTat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("TinhThanhId")
                        .HasColumnType("bigint")
                        .HasColumnName("TinhThanhID");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("Website")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DonViId")
                        .HasName("PK__DM_DONVI__1CB88576D84B4D4C");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("DonViId"), false);

                    b.HasIndex(new[] { "DonViCapChaId" }, "IDX_DM_DONVI_01");

                    b.ToTable("DM_DONVI", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveBalance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApprovalLevel")
                        .HasColumnType("int");

                    b.Property<string>("ApproverRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("LeaveTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveConfigs", t =>
                        {
                            t.HasCheckConstraint("CK_LeaveConfig_ApprovalLevel", "ApprovalLevel >= 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ApprovalLevel = 1,
                            ApproverRole = "QLNP.LD.PCM",
                            LeaveTypeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ApprovalLevel = 2,
                            ApproverRole = "QLNP.GD.PGD",
                            LeaveTypeId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ApprovalLevel = 1,
                            ApproverRole = "QLNP.LD.PCM",
                            LeaveTypeId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ApprovalLevel = 2,
                            ApproverRole = "QLNP.GD.PGD",
                            LeaveTypeId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            ApprovalLevel = 1,
                            ApproverRole = "QLNP.LD.PCM",
                            LeaveTypeId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            ApprovalLevel = 2,
                            ApproverRole = "QLNP.GD.PGD",
                            LeaveTypeId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ApprovalLevel = 1,
                            ApproverRole = "QLNP.LD.PCM",
                            LeaveTypeId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            ApprovalLevel = 1,
                            ApproverRole = "QLNP.LD.PCM",
                            LeaveTypeId = 5L
                        },
                        new
                        {
                            Id = 9L,
                            ApprovalLevel = 2,
                            ApproverRole = "QLNP.GD.PGD",
                            LeaveTypeId = 5L
                        });
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ApprovedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("ApprovedLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<long>("LeaveTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RequestedApproverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveRequestAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("ChangedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("LeaveRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveRequestId");

                    b.ToTable("LeaveRequestAudits");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DefaultDays")
                        .HasColumnType("decimal(5,1)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "NPN",
                            DefaultDays = 12m,
                            Description = "Nghỉ phép năm theo quy định",
                            IsActive = true,
                            Name = "Nghỉ phép năm"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "NO",
                            DefaultDays = 30m,
                            Description = "Nghỉ ốm đau có giấy xác nhận",
                            IsActive = true,
                            Name = "Nghỉ ốm"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "NVR",
                            DefaultDays = 3m,
                            Description = "Nghỉ việc riêng có lương",
                            IsActive = true,
                            Name = "Nghỉ việc riêng"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "NKL",
                            DefaultDays = 0m,
                            Description = "Nghỉ không hưởng lương",
                            IsActive = true,
                            Name = "Nghỉ không lương"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "NTS",
                            DefaultDays = 180m,
                            Description = "Nghỉ thai sản",
                            IsActive = true,
                            Name = "Nghỉ thai sản"
                        });
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.SystemConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConfigKey = "max_annual_leave",
                            ConfigValue = "12",
                            Description = "Số ngày phép năm tối đa",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            ConfigKey = "min_request_days",
                            ConfigValue = "1",
                            Description = "Số ngày tối thiểu khi tạo đơn",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            ConfigKey = "max_carry_over",
                            ConfigValue = "5",
                            Description = "Số ngày phép chuyển sang năm sau",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            ConfigKey = "leave_cycle",
                            ConfigValue = "yearly",
                            Description = "Chu kỳ tính phép",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            ConfigKey = "default_days_CB.PCM",
                            ConfigValue = "14",
                            Description = "Mặc định Cán bộ PCM",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6L,
                            ConfigKey = "default_days_LD.PCM",
                            ConfigValue = "14",
                            Description = "Mặc định Lãnh đạo PCM",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7L,
                            ConfigKey = "default_days_GD.PGD",
                            ConfigValue = "16",
                            Description = "Mặc định Giám đốc PGD",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8L,
                            ConfigKey = "default_days_QTHT",
                            ConfigValue = "12",
                            Description = "Mặc định Quản trị hệ thống",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9L,
                            ConfigKey = "work_days",
                            ConfigValue = "1,2,3,4,5",
                            Description = "Các ngày làm việc trong tuần (0=CN, 1=T2...)",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10L,
                            ConfigKey = "default_leave_type_id",
                            ConfigValue = "1",
                            Description = "Loại phép mặc định khi tạo đơn xin nghỉ",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.UserMaster", b =>
                {
                    b.Property<long>("UserMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("User_MasterID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserMasterId"));

                    b.Property<long?>("CanBoId")
                        .HasColumnType("bigint")
                        .HasColumnName("CanBoID");

                    b.Property<long?>("DonViId")
                        .HasColumnType("bigint")
                        .HasColumnName("DonViID");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("LaDonViChinh")
                        .HasColumnType("bit");

                    b.Property<long?>("PhongBanId")
                        .HasColumnType("bigint")
                        .HasColumnName("PhongBanID");

                    b.Property<bool?>("Used")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("UserPortalId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_PortalID");

                    b.HasKey("UserMasterId")
                        .HasName("PK__USER_MAS__CA9BC5E270CE69C2");

                    b.HasIndex(new[] { "DonViId", "UserPortalId", "Used" }, "IDX_USER_MASTER_01");

                    b.HasIndex(new[] { "UserPortalId" }, "IDX_USER_MASTER_02");

                    b.HasIndex(new[] { "PhongBanId", "DonViId", "UserPortalId" }, "IDX_USER_MASTER_03");

                    b.HasIndex(new[] { "DonViId", "UserPortalId" }, "IDX_USER_MASTER_04");

                    b.HasIndex(new[] { "UserPortalId" }, "IDX_USER_MASTER_05");

                    b.HasIndex(new[] { "DonViId", "UserPortalId" }, "IDX_USER_MASTER_07");

                    b.HasIndex(new[] { "CanBoId", "Used" }, "IX_USER_MASTER_CanBoID_Used");

                    b.ToTable("USER_MASTER", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveConfig", b =>
                {
                    b.HasOne("QLNP.Api.Shared.Domain.LeaveType", "LeaveType")
                        .WithMany("Configs")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveRequest", b =>
                {
                    b.HasOne("QLNP.Api.Shared.Domain.LeaveType", "LeaveType")
                        .WithMany("Requests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveRequestAudit", b =>
                {
                    b.HasOne("QLNP.Api.Shared.Domain.LeaveRequest", "LeaveRequest")
                        .WithMany("Audits")
                        .HasForeignKey("LeaveRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveRequest");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.UserMaster", b =>
                {
                    b.HasOne("QLNP.Api.Shared.Domain.DmDonvi", "DonVi")
                        .WithMany()
                        .HasForeignKey("DonViId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DonVi");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveRequest", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("QLNP.Api.Shared.Domain.LeaveType", b =>
                {
                    b.Navigation("Configs");

                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
